#!/usr/bin/bash

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config normal_border_color $(xrquery bspwm.normal-color)
bspc config focused_border_color $(xrquery bspwm.focused-color)
bspc config active_border_color $(xrquery bspwm.active-color)
bspc config presel_feedback_color $(xrquery bspwm.presel-color)

bspc config automatic_scheme longest_side
bspc config border_width 1
bspc config split_ratio 0.5
bspc config window_gap 14

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config focus_follows_pointer false

bspc rule -a Emacs:emacs state=tiled private=on
bspc rule -a firefox:Navigator private=on
bspc rule -a Nm-connection-editor:nm-connection-editor state=floating
bspc rule -a Zathura state=tiled

bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/external-rules"

restart polybar main &
