#!/usr/bin/bash

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config normal_border_color "#242730"
bspc config focused_border_color "#51afef"
bspc config active_border_color "#242730"
bspc config presel_feedback_color "#51afef"

bspc config border_width 1
bspc config split_ratio  0.5
bspc config window_gap   14

bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc config focus_follows_pointer true

bspc config automatic_scheme longest_side

bspc rule -a Emacs state=tiled

~/.config/polybar/launch.sh
