;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        anzu-query-replace
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        evil-backward-char
        evil-delete-char
        evil-emacs-state
        evil-forward-char
        evil-insert
        evil-next-line
        evil-previous-line
        evil-replace
        evil-scroll-line-down
        evil-search-forward
        evil-visual-char
        evil-yank
        hs-hide-block
        indent-for-tab-command
        markdown-cycle
        markdown-outdent-or-delete
        org-beginning-of-line
        panda/C-w
        powershell-indent-line
        repeat
        typescript-insert-and-indent
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        evil-goto-mark-line
        hydra--digit-argument
        hydra--negative-argument
        hydra-evil-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/body
        hydra-multiple-cursors/lambda-/-and-exit
        hydra-multiple-cursors/mc/edit-lines
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/nil
        ivy-alt-done
        mouse-set-region
        nlinum-mode
        org-self-insert-command
        projectile-switch-project
        smex
        suspend-frame
        toggle-input-method
        ))
