;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        evil-previous-line
        hs-hide-block
        indent-for-tab-command
        panda/C-w
        repeat
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        evil-forward-char
        hydra-evil-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/edit-lines
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/nil
        ivy-alt-done
        mouse-set-region
        projectile-switch-project
        smex
        ))
