#!/usr/bin/bash

info=$(cmus-remote -Q 2> /dev/null)

if [[ $? != 0 ]]; then
	echo ""
	exit
fi

status=$(echo "$info" | grep "^status " | cut -d" " -f2-)
title=$(echo "$info" | grep "^tag title " | cut -d" " -f3-)

case $status in
    playing) echo " $title" ;;
    paused)  echo "契 $title" ;;
    stopped) echo "栗 stopped" ;;
    *)       echo "" ;;
esac
