#define BACKGROUND #1B2B34
#define FOREGROUND #D8DEE9
#define BLACK      #343D46
#define RED        #EC5F67
#define GREEN      #99C794
#define YELLOW     #FAC863
#define BLUE       #6699CC
#define MAGENTA    #C594C5
#define CYAN       #5FB3B3
#define WHITE      #D8DEE9

#define CURSOR_COLOR RED

#define i3_BACKGROUND     BACKGROUND
#define i3_FOREGROUND     FOREGROUND
#define i3_ACTIVE_COLOR   GREEN
#define i3_INACTIVE_COLOR BLUE
#define i3_URGENT_COLOR   RED

#define ROFI_BACKGROUND      BACKGROUND
#define ROFI_FOREGROUND      FOREGROUND
#define ROFI_BORDER_COLOR    GREEN
#define ROFI_SEPARATOR_COLOR GREEN
#define ROFI_ACTIVE_HL_BG    YELLOW
#define ROFI_ACTIVE_HL_FG    BACKGROUND
#define ROFI_SELECT_HL_BG    GREEN
#define ROFI_SELECT_HL_FG    BACKGROUND
#define ROFI_URGENT_HL_BG    RED
#define ROFI_URGENT_HL_FG    BACKGROUND
