#define BACKGROUND #000000
#define FOREGROUND #FFFFFF
#define BLACK      #191919
#define RED        #D41919
#define GREEN      #17917A
#define YELLOW     #FFD86E
#define BLUE       #367BF0
#define MAGENTA    #9655AE
#define CYAN       #47AFE2
#define WHITE      #FFFFFF

#define CURSOR_COLOR GREEN

#define i3_BACKGROUND     BACKGROUND
#define i3_FOREGROUND     FOREGROUND
#define i3_ACTIVE_COLOR   GREEN
#define i3_INACTIVE_COLOR BLUE
#define i3_URGENT_COLOR   RED

#define ROFI_BACKGROUND      BACKGROUND
#define ROFI_FOREGROUND      FOREGROUND
#define ROFI_BORDER_COLOR    GREEN
#define ROFI_SEPARATOR_COLOR GREEN
#define ROFI_ACTIVE_HL_BG    YELLOW
#define ROFI_ACTIVE_HL_FG    BACKGROUND
#define ROFI_SELECT_HL_BG    GREEN
#define ROFI_SELECT_HL_FG    FOREGROUND
#define ROFI_URGENT_HL_BG    RED
#define ROFI_URGENT_HL_FG    FOREGROUND
